# Here is the full list of customizable features
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

linters:
  enable:
    - errcheck                  # Errcheck is a program for checking for unchecked errors in go programs.
    - gocheckcompilerdirectives # Checks that go compiler directive comments (//go:) are valid.
    - gofmt                     # Gofmt checks whether code was gofmt-ed.
    - gosimple                  # Linter for Go source code that specializes in simplifying code
    - govet                     # Vet examines Go source code and reports suspicious constructs
    - ineffassign               # Detects when assignments to existing variables are not used
    - staticcheck               # Set of rules from staticcheck.
    - typecheck                 # Like the front-end of a Go compiler, parses and type-checks Go code
    - unused                    # Checks Go code for unused constants, variables, functions and types

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
