# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - sh ./scripts/gen_manpages.sh
    - go install github.com/goreleaser/chglog/cmd/chglog@latest
    - chglog init

builds:
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildmode=pie
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: windows-startup
    main: ./tools/windows-startup/main.go
    binary: windows-startup
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildmode=pie
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: windows-service
    main: ./tools/windows-service/main.go
    binary: windows-service
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildmode=pie
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: windows-health-monitor
    main: ./tools/health-monitor/main.go
    binary: cfusemon
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildmode=pie
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/lib/x86_64-linux-gnu
      - CC=zig cc -target x86_64-linux-gnu -isystem /usr/lib/x86_64-linux-gnu -iwithsysroot /usr/include
      - CXX=zig c++ -target x86_64-linux-gnu -isystem /usr/lib/x86_64-linux-gnu -iwithsysroot /usr/include
    flags:
      - -trimpath
      - -buildmode=pie
      # - -tags=fuse3
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }} -L /usr/lib/x86_64-linux-gnu

  - id: linux-amd64-health-monitor
    main: ./tools/health-monitor/main.go
    binary: cfusemon
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildmode=pie
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/lib/aarch64-linux-gnu
      - CC=zig cc -target aarch64-linux-gnu -isystem /usr/lib/aarch64-linux-gnu -iwithsysroot /usr/include
      - CXX=zig c++ -target aarch64-linux-gnu  -isystem /usr/lib/aarch64-linux-gnu -iwithsysroot /usr/include
    flags:
      - -trimpath
      - -buildmode=pie
      # - -tags=fuse3
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: linux-arm64-health-monitor
    main: ./tools/health-monitor/main.go
    binary: cfusemon
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildmode=pie
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

checksum:
  name_template: "checksums_sha256.txt"
  algorithm: sha256

archives:
  - id: linux-amd64
    ids:
      - linux-amd64
      - linux-amd64-health-monitor
    formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md
      - NOTICE
      - src: ./gui/dist/cloudfuseGUI_Linux/*
        dst: ./
      - src: setup/baseConfig.yaml
        dst: ./samples/baseConfig.yaml
      - src: sample_configs/*
        dst: ./samples/

  - id: linux-amd64_no_gui
    ids:
      - linux-amd64
      - linux-amd64-health-monitor
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_no_gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - NOTICE
      - src: setup/baseConfig.yaml
        dst: ./samples/baseConfig.yaml
      - src: sample_configs/*
        dst: ./samples/

  - id: linux-arm64_no_gui
    ids:
      - linux-arm64
      - linux-arm64-health-monitor
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_no_gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - NOTICE
      - src: setup/baseConfig.yaml
        dst: ./samples/baseConfig.yaml
      - src: sample_configs/*
        dst: ./samples/

  - id: windows
    ids:
      - windows
      - windows-startup
      - windows-health-monitor
      - windows-service
    formats: ["zip"]
    files:
      - LICENSE
      - README.md
      - NOTICE
      - src: ./gui/dist/cloudfuseGUI_Windows/*
        dst: ./
      - src: setup/baseConfig.yaml
        dst: ./samples/baseConfig.yaml
      - src: sample_configs/*
        dst: ./samples/

  - id: windows_no_gui
    ids:
      - windows
      - windows-startup
      - windows-health-monitor
      - windows-service
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_no_gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - NOTICE
      - src: setup/baseConfig.yaml
        dst: ./samples/baseConfig.yaml
      - src: sample_configs/*
        dst: ./samples/

release:
  extra_files:
    - glob: ./build/Output/cloudfuse_{{.Version}}_windows_amd64.exe
    - glob: ./build/Output/cloudfuse_no_gui_{{.Version}}_windows_amd64.exe

nfpms:
  - id: linux
    package_name: cloudfuse
    ids:
      - linux-amd64
    vendor: Seagate Technology
    homepage: https://github.com/Seagate/cloudfuse
    maintainer: Seagate Technology <cloudfuse@seagate.com>
    description: |-
      FUSE file system for interacting with S3 and Azure storage
      Cloudfuse provides the ability to mount a cloud bucket in your local file
      system. You can easily read and write to the cloud, and connect programs
      on your computer to the cloud even if they're not cloud-aware.
    license: MIT
    changelog: "changelog.yml"
    formats:
      - deb
      - rpm
    section: utils

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      - src: './dist/linux-{{ .Arch }}-health-monitor_linux_{{ .Arch }}{{- if eq .Arch "amd64" }}_{{ .Amd64 }}{{- else }}_{{ .Arm64 }}{{ end }}/cfusemon'
        dst: /usr/bin/cfusemon
        file_info:
          mode: 0755
      - src: NOTICE
        dst: /usr/share/doc/cloudfuse/NOTICE
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/cloudfuse/LICENSE
        file_info:
          mode: 0644
      - src: copyright
        dst: /usr/share/doc/cloudfuse/copyright
        file_info:
          mode: 0644
      - src: setup/baseConfig.yaml
        dst: /usr/share/doc/cloudfuse/examples/baseConfig.yaml
        file_info:
          mode: 0644
      - src: sample_configs/*
        dst: /usr/share/doc/cloudfuse/examples/
        file_info:
          mode: 0644
      - src: ./manpages/*
        dst: /usr/share/man/man1/
        file_info:
          mode: 0644

    overrides:
      deb:
        dependencies:
          - fuse3
          - libc6 (>= 2.24)

      rpm:
        dependencies:
          - fuse3
          - glibc >= 2.24

  - id: linux_no_gui
    package_name: cloudfuse
    ids:
      - linux-amd64
      - linux-arm64
    file_name_template: "{{ .ProjectName }}_no_gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: Seagate Technology
    homepage: https://github.com/Seagate/cloudfuse
    maintainer: Seagate Technology <cloudfuse@seagate.com>
    description: |-
      FUSE file system for interacting with S3 and Azure storage
      Cloudfuse provides the ability to mount a cloud bucket in your local file
      system. You can easily read and write to the cloud, and connect programs
      on your computer to the cloud even if they're not cloud-aware.
    license: MIT
    changelog: "changelog.yml"
    formats:
      - deb
      - rpm
    section: utils
    contents:
      - src: './dist/linux-{{ .Arch }}-health-monitor_linux_{{ .Arch }}{{- if eq .Arch "amd64" }}_{{ .Amd64 }}{{- else }}_{{ .Arm64 }}{{ end }}/cfusemon'
        dst: /usr/bin/cfusemon
        file_info:
          mode: 0755
      - src: NOTICE
        dst: /usr/share/doc/cloudfuse/NOTICE
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/cloudfuse/LICENSE
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/cloudfuse/README
        file_info:
          mode: 0644
      - src: copyright
        dst: /usr/share/doc/cloudfuse/copyright
        file_info:
          mode: 0644
      - src: setup/baseConfig.yaml
        dst: /usr/share/doc/cloudfuse/examples/baseConfig.yaml
        file_info:
          mode: 0644
      - src: sample_configs/*
        dst: /usr/share/doc/cloudfuse/examples/
        file_info:
          mode: 0644
      - src: ./manpages/*
        dst: /usr/share/man/man1/
        file_info:
          mode: 0644

    overrides:
      deb:
        dependencies:
          - fuse3
          - libc6 (>= 2.24)

      rpm:
        dependencies:
          - fuse3
          - glibc >= 2.24

signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "${artifact}"
      - "--bundle=${signature}"
      - "--yes"
    artifacts: checksum
    signature: "${artifact}.bundle"
    env:
      - COSIGN_EXPERIMENTAL=1

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
