# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}
    
  - id: windows-startup
    main: ./tools/windows-startup/main.go
    binary: windows-startup
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}
    
  - id: windows-health-monitor
    main: ./tools/health-monitor/main.go
    binary: cfusemon
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/lib/x86_64-linux-gnu
      - CC=zig cc -target x86_64-linux-gnu -isystem /usr/lib/x86_64-linux-gnu -iwithsysroot /usr/include
      - CXX=zig c++ -target x86_64-linux-gnu -isystem /usr/lib/x86_64-linux-gnu -iwithsysroot /usr/include
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }} -L /usr/lib/x86_64-linux-gnu

  - id: linux-amd64-health-monitor
    main: ./tools/health-monitor/main.go
    binary: cfusemon
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/lib/aarch64-linux-gnu
      - CC=zig cc -target aarch64-linux-gnu -isystem /usr/lib/aarch64-linux-gnu -iwithsysroot /usr/include
      - CXX=zig c++ -target aarch64-linux-gnu  -isystem /usr/lib/aarch64-linux-gnu -iwithsysroot /usr/include
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

  - id: linux-arm64-health-monitor
    main: ./tools/health-monitor/main.go
    binary: cfusemon
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X github.com/Seagate/cloudfuse/common.GitCommit={{.Commit}} -X github.com/Seagate/cloudfuse/common.CommitDate={{ .CommitDate }}

checksum:
  name_template: "checksums_sha256.txt"
  algorithm: sha256

release:
  extra_files: 
    - glob: ./build/Output/cloudfuse_{{.Version}}_windows_amd64.exe
    - glob: ./build/Output/cloudfuse_no_gui_{{.Version}}_windows_amd64.exe

nfpms:
  - id: linux

    # Name of the package.
    package_name: cloudfuse

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults empty, which means no filtering.
    builds:
      - linux-amd64

    vendor: Seagate Technology
    homepage: https://github.com/Seagate/cloudfuse
    maintainer: https://github.com/Seagate/cloudfuse
    description: |-
      A FUSE filesystem for interacting with S3 and Azure storage.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    section: default

    provides:
      - cloudfuse
      - cfusemon

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      # Basic file that applies to all packagers
      - src: './dist/linux-{{ .Arch }}-health-monitor_linux_{{ .Arch }}{{- if eq .Arch "amd64" }}_{{ .Amd64 }}{{- else }}{{ end }}/cfusemon'
        dst: /usr/bin/cfusemon
      - src: NOTICE
        dst: /usr/share/doc/cloudfuse/NOTICE
      - src: LICENSE
        dst: /usr/share/doc/cloudfuse/LICENSE
      - src: setup/baseConfig.yaml
        dst: /usr/share/doc/cloudfuse/examples/baseConfig.yaml
      - src: sampleFileCacheConfigAzure.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleFileCacheConfigAzure.yaml
      - src: sampleFileCacheConfigS3.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleFileCacheConfigS3.yaml
      - src: sampleFileCacheWithSASConfigAzure.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleFileCacheWithSASConfigAzure.yaml
      - src: sampleStreamingConfigS3.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleStreamingConfigS3.yaml
      - src: sampleStreamingConfigAzure.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleStreamingConfigAzure.yaml

      - src: ./gui/cloudfuse.desktop
        dst: /usr/share/applications/cloudfuse.desktop
      - src: "./gui/dist/cloudfuseGUI_Linux/*"
        dst: "/opt/cloudfuse"
  
    overrides:
      deb:
        dependencies:
          - libfuse3-dev

      rpm:
        dependencies:
          - fuse3-devel

  - id: linux_no_gui

    # Name of the package.
    package_name: cloudfuse

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults empty, which means no filtering.
    builds:
      - linux-amd64
      - linux-arm64
    file_name_template: "{{ .ProjectName }}_no_gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: Seagate Technology
    homepage: https://github.com/Seagate/cloudfuse
    maintainer: https://github.com/Seagate/cloudfuse
    description: |-
      A FUSE filesystem for interacting with S3 and Azure storage.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    section: default

    provides:
      - cloudfuse
      - cfusemon

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      # Basic file that applies to all packagers
      - src: './dist/linux-{{ .Arch }}-health-monitor_linux_{{ .Arch }}{{- if eq .Arch "amd64" }}_{{ .Amd64 }}{{- else }}{{ end }}/cfusemon'
        dst: /usr/bin/cfusemon
      - src: NOTICE
        dst: /usr/share/doc/cloudfuse/NOTICE
      - src: LICENSE
        dst: /usr/share/doc/cloudfuse/LICENSE
      - src: setup/baseConfig.yaml
        dst: /usr/share/doc/cloudfuse/examples/baseConfig.yaml
      - src: sampleFileCacheConfigAzure.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleFileCacheConfigAzure.yaml
      - src: sampleFileCacheConfigS3.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleFileCacheConfigS3.yaml
      - src: sampleFileCacheWithSASConfigAzure.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleFileCacheWithSASConfigAzure.yaml
      - src: sampleStreamingConfigS3.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleStreamingConfigS3.yaml
      - src: sampleStreamingConfigAzure.yaml
        dst: /usr/share/doc/cloudfuse/examples/sampleStreamingConfigAzure.yaml
  
    overrides:
      deb:
        dependencies:
          - libfuse3-dev

      rpm:
        dependencies:
          - fuse3-devel

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
