# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  # Test suite
  - job: test
    displayName: Build and Test on
    strategy:
      matrix:
        Ubuntu-20:
          imageName: 'windows-latest'
          containerName: 'test-cnt-ubn-20'
          adlsSas: $(AZTEST_ADLS_CONT_SAS_UBN_20)
  
    pool:
      vmImage: $(imageName)
    variables:
      - group: NightlyLyveCloudFuse

    steps:
    - checkout: self

    - task: GoTool@0
      inputs:
        version: '1.19.6'
      displayName: "Select Go Version"

    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d ./...'
        workingDirectory: './'
      displayName: "Get Dependencies"

    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: ./
        arguments: "-tags $(tags) -o lyvecloudfuse"
      displayName: "Build"

    - script: |
        install_winfsp.bat
      displayName: "Install WinFSP"
      continueOnError: false
      workingDirectory: ./

    - script: |
        cnfFile=$HOME/azuretest.json
        echo $cnfFile
        touch $cnfFile
        echo "{" > $cnfFile
        echo "\"block-acct\"": "\"$(AZTEST_BLOCK_ACC_NAME)\"", >> $cnfFile
        echo "\"adls-acct\"": "\"$(AZTEST_ADLS_ACC_NAME)\"", >> $cnfFile
        echo "\"block-cont\"": "\"$(containerName)\"", >> $cnfFile
        echo "\"adls-cont\"": "\"$(containerName)\"", >> $cnfFile
        echo "\"block-key\"": "\"$(AZTEST_BLOCK_KEY)\"", >> $cnfFile
        echo "\"adls-key\"": "\"$(AZTEST_ADLS_KEY)\"", >> $cnfFile
        echo "\"block-sas\"": "\"$(AZTEST_BLOCK_SAS)\"", >> $cnfFile
        echo "\"block-cont-sas-ubn-18\"": "\"$(AZTEST_BLOCK_CONT_SAS_UBN_18)\"", >> $cnfFile
        echo "\"block-cont-sas-ubn-20\"": "\"$(AZTEST_BLOCK_CONT_SAS_UBN_20)\"", >> $cnfFile
        echo "\"adls-sas\"": "\"$(adlsSas)\"", >> $cnfFile
        echo "\"msi-appid\"": "\"$(AZTEST_APP_ID)\"", >> $cnfFile
        echo "\"msi-resid\"": "\"$(AZTEST_RES_ID)\"", >> $cnfFile
        echo "\"msi-objid\"": "\"$(AZTEST_OBJ_ID)\"", >> $cnfFile
        echo "\"spn-client\"": "\"$(AZTEST_CLIENT)\"", >> $cnfFile
        echo "\"spn-tenant\"": "\"$(AZTEST_TENANT)\"", >> $cnfFile
        echo "\"spn-secret\"": "\"$(AZTEST_SECRET)\"", >> $cnfFile
        echo "\"skip-msi\"": "true", >> $cnfFile
        echo "\"proxy-address\"": "\"\"" >> $cnfFile
        echo "}" >> $cnfFile
        cat $cnfFile
      displayName: "Create Configuration File"
      continueOnError: false
      workingDirectory: ./

    # Running unit tests on Windows
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v -timeout=2h ./... --tags=unittest,$(tags) -coverprofile utcover.cov'
      displayName: 'Unit tests'
      condition: always()
