pr:
- main


trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:

  - checkout: self

  - task: GoTool@0
    inputs:
      version: '1.19.6'
    displayName: "Select Go Version"
    
  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-d ./...'
      workingDirectory: './'
    displayName: "Get Dependencies"

  

  - script: |
      ./TrivySetup.sh
    displayName: 'Install Trivy'

  - script: |
        ./RunTrivyScans.sh
    displayName: 'Run Trivy scans'

