# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pr:
- main
jobs:
  # Windows based test suite
  - job: test
    displayName: Build and Test on
    strategy:
      matrix:
        Windows-Latest:
          imageName: 'windows-latest'
          containerName: 'test-windows-latest'
  
    pool:
      vmImage: $(imageName)
    variables:
      - group: NightlyLyveCloudFuse
    steps:
    - checkout: self
    - task: GoTool@0
      inputs:
        version: '1.20.5'
      displayName: "Select Go Version"
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d ./...'
        workingDirectory: './'
      displayName: "Get Dependencies"
    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: ./
        arguments: "-o lyvecloudfuse.exe"
      displayName: "Build"
      env:
        CGO_ENABLED: 0
    - powershell: |
        $cnfFile="~\azuretest.json"
        Write-Host $cnfFile
        $content = @"
        {
          "block-acct": "$(AZTEST_BLOCK_ACC_NAME)",
          "adls-acct": "$(AZTEST_ADLS_ACC_NAME)",
          "block-cont": "$(containerName)",
          "adls-cont": "$(containerName)",
          "block-key": "$(AZTEST_BLOCK_KEY)",
          "adls-key": "$(AZTEST_ADLS_KEY)",
          "block-sas": "$(AZTEST_BLOCK_SAS)",
          "block-cont-sas-ubn-18": "$(AZTEST_BLOCK_CONT_SAS_UBN_18)",
          "block-cont-sas-ubn-20": "$(AZTEST_BLOCK_CONT_SAS_UBN_20)",
          "adls-sas": "$(AZTEST_ADLS_SAS)",
          "msi-appid": "$(AZTEST_APP_ID)",
          "msi-resid": "$(AZTEST_RES_ID)",
          "msi-objid": "$(AZTEST_OBJ_ID)",
          "spn-client": "$(AZTEST_CLIENT)",
          "spn-tenant": "$(AZTEST_TENANT)",
          "spn-secret": "$(AZTEST_SECRET)",
          "skip-msi": true,
          "proxy-address": ""
        }
        "@
        $content | Out-File -FilePath $cnfFile -Encoding Ascii
        Get-Content $cnfFile
      displayName: "Create Configuration File"
      continueOnError: false
      workingDirectory: ./
    # Running unit tests
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v -timeout=2h ./... --tags=unittest,$(tags) -coverprofile utcover.cov'
      displayName: 'Unit tests'
      condition: always()
      env:
        CGO_ENABLED: 0
        