# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - s3storage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /home/myuser/tempcache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200

s3storage:
  bucket-name: mystorageaccount
  key-id: mystoragekey
  secret-key: mystoragesecretkey
  endpoint: https://s3.us-east-1.lyvecloud.seagate.com
  region: us-east-1
