# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  path: /<PATH>/<TO>/<CACHE_DIR>
  timeout-sec: 120
  max-size-mb: 4096
  allow-non-empty-temp: true

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  account-name: <ACCOUNT_NAME>
  sas: <SAS_TOKEN>
  endpoint: https://<ACCOUNT_NAME>.blob.core.windows.net
  mode: sas
  container: <CONTAINER_NAME>
 