foreground: false
allow-other: true
logging:
  level: log_debug
  file-path: lyvecloudfuse-logs.txt
  type: base
components:
- libfuse
- file_cache
- attr_cache
- azstorage
libfuse:
  default-permission: 511
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  ignore-open-flags: true
file_cache:
  path: ''
  timeout-sec: 240
  max-size-mb: 4096
  create-empty-file: true
attr_cache:
  timeout-sec: 7200
azstorage:
  type: block
  account-name: ''
  account-key: ''
  endpoint: ''
  mode: key
  container: ''
