# Refer ./setup/baseConfig.yaml for full set of config parameters

config-version: 1.0.0

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - stream
  - attr_cache
  - s3storage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240
  network-share: true

stream:
  block-size-mb: 8
  blocks-per-file: 3
  cache-size-mb: 1024

attr_cache:
  timeout-sec: 7200

s3storage:
  bucket-name: <ACCOUNT_NAME>
  key-id: <ACCOUNT_ACCESS_KEY>
  secret-key: <ACCOUNT_SECRET_KEY>
  endpoint: https://s3.us-east-1.lyvecloud.seagate.com
  region: us-east-1
  enable-dir-marker: true
