# Refer ./setup/baseConfig.yaml for full set of config parameters

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - s3storage

libfuse:
  network-share: true

file_cache:
  path: /<PATH>/<TO>/<CACHE_DIR>
  timeout-sec: 64000000
  allow-non-empty-temp: true
  ignore-sync: true

attr_cache:
  timeout-sec: 7200

s3storage:
  bucket-name: <ACCOUNT_NAME>
  key-id: <ACCOUNT_ACCESS_KEY>
  secret-key: <ACCOUNT_SECRET_KEY>
  endpoint: https://s3.us-east-1.lyvecloud.seagate.com
  region: us-east-1
  enable-dir-marker: true
